import React from "react";
import ExternalLink from "../../components/ExternalLink";
import Layout from "../../components/Layout";

export default function Siba(): JSX.Element {
  return (
    <Layout>
      <h1>Simulation International Basketball Association</h1>
      <div className="columns is-reversed">
        <div className="column">
          <p className="is-size-5-tablet">
            The Simulation Internet Basketball Association (SIBA) is a fictional
            basketball league created by the father-daughter team of Kelley and
            Brittani Avery and powered by the pro and college basketball games
            from{" "}
            <ExternalLink href="https://www.wolverinestudios.com/">
              Wolverine Studios
            </ExternalLink>
            .
          </p>

          <h2>Background</h2>
          <p>
            This started out as a way for my father and I bond over our love for
            basketball and statistics. We needed a place to put the rules,
            standings, and other information required to run a successful
            league. I decided to use this opportunity as a way to learn more
            about React and AWS as well as hone my skills as a graphic artist.
            For the pro league logo, I used{" "}
            <ExternalLink href="https://unsplash.com/photos/Iil35il081Y">
              a photo by Logan Weaver
            </ExternalLink>{" "}
            as a reference, liking the end result. I kept the college logo
            simple and generic since college sports (usually) have more focus on
            the teams rather than individual players.
          </p>
          <h2>Join the Fun</h2>
          <p>
            If you&apos;re interested in joining either the pro and college
            leagues, be sure to visit the website and check out the rules. There
            are plenty of teams left.{" "}
            <span className="iconify" data-icon="noto:smiling-face" />
          </p>
          <p>
            If you&apos;re a fellow developer, check out the code on Github. I
            would love some suggestions on how to better integrate the files
            generated by the Wolverine Studios games.
          </p>
          <div className="buttons">
            <ExternalLink
              href="http://siba.averyincorporated.com/"
              className="button is-primary"
            >
              Visit SIBA
            </ExternalLink>
            <ExternalLink
              href="https://github.com/brittaniSavery/siba-league-site"
              className="button is-primary is-light"
            >
              View Code
            </ExternalLink>
          </div>
        </div>
        <div className="column is-narrow">
          <img
            src="https://via.placeholder.com/350x445.jpg?text=Logos"
            alt="Logos for pro and college leagues of SIBA"
          />
        </div>
      </div>
    </Layout>
  );
}
