name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 45 9 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: squash
          # Added time zone to account for Mailchimp automation
          time_zone: "America/Chicago"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
